#!/bin/zsh

TEST_PROMPT='(237;223)%n>'
TEST_PROMPT+='(214)?1j;%%%j>'
TEST_PROMPT+='(208;237)!%!>'
TEST_PROMPT+='(109;237)%4~>'
TEST_PROMPT+='(142;237)?$($HOME/bin/install/pretty-git-prompt/target/release/pretty-git-prompt -c $HOME/bin/config/pretty-git-prompt-zsh.yml)>'
TEST_PROMPT+='(72;237)?$(get_venv_name_prompt)>'
TEST_PROMPT+='(0)\n|(241)??;%F{250} √;%F{88}%?<'
TEST_PROMPT+='(0;0)%k%f%(!.#.)'

TMP=$(target/debug/zsh-theme $TEST_PROMPT)

for l in $TMP; do
   eval $l
done

